/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fotoUrl', 'googleId', 'id', 'nama', 'noHp', 'passwordHash', 'role', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fotoUrl: string | null
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nama: string
  @column()
  declare noHp: string | null
  @column()
  declare passwordHash: string | null
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WargaProfileSchema extends BaseModel {
  static $columns = ['alamat', 'createdAt', 'fotoKtpUrl', 'id', 'kk', 'nik', 'noRumah', 'rejectionReason', 'statusHuni', 'updatedAt', 'userId', 'verificationStatus', 'verifiedAt', 'verifiedBy'] as const
  $columns = WargaProfileSchema.$columns
  @column()
  declare alamat: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fotoKtpUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kk: string | null
  @column()
  declare nik: string | null
  @column()
  declare noRumah: string | null
  @column()
  declare rejectionReason: string | null
  @column()
  declare statusHuni: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
  @column()
  declare verificationStatus: string
  @column.dateTime()
  declare verifiedAt: DateTime | null
  @column()
  declare verifiedBy: string | null
}
